accounts/urls.py
'''
Created on Apr 29, 2018

@author: S528358
'''
from django.urls import path, re_path
from . import views as core_views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [    
   path('sign_up',core_views.sign_up, name = 'sign_up'),
#     path('login',core_views.login_view, name='login_view'),
    path('login',core_views.login_view, name='login_view'),
   path('logout',auth_views.logout,{'next_page': '/accounts/login'}, name='logout_view'),
    re_path(r'^(?P<slug>[\w-]+)$', core_views.profile_page, name = 'profile_page'),
    re_path(r'^(?P<slug>[\w-]+)/delete$', core_views.article_delete, name = 'article_delete'),
]

articles/urls.py
'''
Created on Apr 28, 2018

@author: S528358
'''
from django.urls import path, re_path
from . import views
app_name = 'articles'
urlpatterns = [   
    path('', views.article_list, name = 'article_list'),
    path('create',views.article_create, name = 'article_create'),
    re_path(r'^(?P<slug>[\w-]+)$', views.article_delete, name = 'article_delete'),
    re_path(r'^(?P<slug>[\w-]+)/update$', views.article_update, name = 'article_update'),    
    re_path(r'^(?P<slug>[\w-]+)/detail$', views.article_detail, name = 'article_detail'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include, re_pathfrom . import views
from articles import views as article_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about, name = 'about'),
    path('', views.homepage, name = 'homepage'),
#     re_path(r'^(?P<slug>[\w-]+)/$',views.homepage, name = 'homepage' ),
   
]

accounts/models.py
from django.db import models

# Create your models here.
from articles.models import Article

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.utils.text import slugify
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 100)
    body = models.TextField()
    slug = models.SlugField(unique=True)
    time = models.DateTimeField(auto_now_add=True)
    pic = models.ImageField(null=True, blank=True)    
    authorid = models.ForeignKey(User,models.SET_NULL,blank=True,null=True)   
    
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:30]+'...'
    
    def get_absolute_url(self):
        return '/accounts/%s' %self.authorid

def create_slug(instance, new_slug=None):
        slug = slugify(instance.title)
        if new_slug is not None:
            slug = new_slug
        qs = Article.objects.filter(slug=slug)
        exists = qs.exists()
        if exists:
            new_slug = "%s-%s" %(slug, qs.first().id)
            return create_slug(instance, new_slug=new_slug)
        return slug
def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    
pre_save.connect(pre_save_post_receiver, sender=Article)

articles/forms.py
'''
Created on May 3, 2018

@author: S528358
'''
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body','pic']

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .models import Article
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('accounts:profile_page',slug=user)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/sign_up.html',{'form':form})

def login_view(request, slug=None):
   
#     print(request.GET.urlencode())
    if request.method == 'POST':
        print('login user',slug)
        print('login_view',request.user)
        print(request.POST)
        print('username' in request.POST)
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))            
            else:
                return redirect('accounts:profile_page',slug=user)
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):    
    logout(request)
    return redirect('')
#     return redirect('accounts:login_view')

@login_required(login_url='/accounts/login')
def article_delete(request, slug=None):
    print(slug)
    user = request.user
    print('user delete',user)
    obj = Article.objects.get(slug=slug,authorid=user)
    print('delete',obj.slug)
    obj.delete()
    return redirect('accounts:profile_page',slug=user)

@login_required(login_url='/accounts/login')
def profile_page(request,slug=None):
    print('calling profil page',request.method)
    print('logged in as',request.user)
    print('slug is',slug)
    obj = Article.objects.all()
    users = User.objects.all()    
    ans = []
    for i in obj:
        if str(i.authorid) == str(slug):
            ans.append(i)
    context = {
        'obj':obj,
        'ans':ans,
        }
    for i in users:
        print(i)
#     print(request.user in users)
    print(ans)

#     print(ans[0].authorid)

#    print(ans[0].authorid)

    if str(request.user) == str(slug):
        return render(request, 'accounts/profile.html', {'ans':ans})
    else:
        return render(request, 'accounts/guest_profile.html', {'ans':ans})

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
from django.utils.text import slugify
from articles.forms import CreateArticle
# Create your views here.
@login_required(login_url='/accounts/login')
def article_list(request):
    obj = Article.objects.all().order_by('time')
    return render(request, 'articles/article_list.html', {'obj':obj})

def article_delete(request,slug=None):
    article = Article.objects.get(slug=slug)
    user = article.authorid
    article.delete()    
    return redirect(request, 'accounts:profile_page', slug=user)

@login_required(login_url='/accounts/login')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST or None,request.FILES or None)
        if form.is_valid():            
            instance = form.save(commit=False)
            print('slug present ?',instance.slug)
            instance.authorid = request.user
            instance.slug = slugify(instance.slug)
            print('slug=',instance.slug)
            instance.save()
            print('Logged in user',instance.authorid)
            return redirect('accounts:profile_page', slug=instance.authorid)
    else:
        form = forms.CreateArticle()
    return render(request,'articles/article_create.html', {'form':form})
    
    
def article_update(request,slug=None):
    instance = Article.objects.get(slug=slug)
    print(instance.title)
    form = forms.CreateArticle(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        return redirect('accounts:profile_page', slug=instance.authorid)
    context = {
        'title':instance.title,
        'instance':instance,
        'form':form,
        }
    return render(request,'articles/article_create.html', {'form':form})

def article_detail(request,slug=None):
    print('detail slug',slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article':article})

djangonautic/views.py
'''
Created on Apr 27, 2018

@author: S528358
'''
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
#     return HttpResponse('about')
    return render(request, 'about.html')

def homepage(request):
#     return HttpResponse('home')
    print(request.user)
    username = request.user
    return render(request, 'homepage.html',{'username':username})

accounts/templates/accounts/guest_profile.html
{% extends 'base.html' %}

{% block content %}



<p>
<h2> You are logged in as <h1>{{user}}</h1></h2>
<h2><a class ="btn btn-primary" href = "{% url 'accounts:profile_page' slug=user %}">Home</a>
<!-- <ul nav class="nav nav-pills"> -->
<!-- 	<li class="nav-item"> -->
<!--   <a class="nav-link active" href="{% url 'articles:article_create' %}">Create Post</a> -->
<!--   </li> -->
<!--   <ul> -->
<h1>Welcome to another user's Blog</h1>


{% if ans %}


{% for i in ans %}
		
<div class="row-sm-20">
  <div class="col-sm-20"> 
<div class="card" style="width: 18rem;">
	{% if i.pic %}	
	<img class="card-img-top" src="{{i.pic.url}}" alt="Card image cap">	
	{% endif %}
 
	<div class="card-body">
		<a class="card-title" href = "{%url 'articles:article_detail' slug=i.slug %}">{{i.title}}</a>
		<p class="card-text">{{i.snippet}}</p>
		<p class="card-text">{{i.time}}</p>
		
<!-- 		<div class="btn-group" role="group" aria-label="Basic example"> -->
		
<!--     		<a class ="btn btn-primary" href = "{%url 'accounts:article_delete' slug=i.slug %}">Delete Post</a> -->
<!--     		<a class ="btn btn-primary" href = "{%url 'articles:article_update' slug=i.slug %}">Update Post</a> -->
    		
<!--     	</div> -->
    </div>  
  </div>
</div>
{% endfor %}
{% endif %}
</div>
</p>

{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
<style>
h2{
text-align:center;
}
form{
text-align:center;
}
</style>
</head>
<body>

<h2>LOGIN</h2>
<form  action = "/accounts/login" method ='post'>
<div class = "form-group"> 
{% csrf_token %}
{{form.as_p}}
{% if request.GET.next %}
	<input type='hidden' name = 'next' value = '{{request.GET.next}}'>
{% endif %}
</div>
<input class="btn btn-primary" type="submit" value="Login">
</form>
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<style>
h2,h3{
text-align:center;
}
h3{
text-align:center;
}
#user{
color:green;
}
.card{
bottom-margin: 10px;
}
</style>

<p>
{% if user.is_authenticated %}
<h2> You are logged in as <span id="user">{{user}}</span></h2>
{% endif %}
<ul nav class="nav nav-pills">
	<li class="nav-item">
  <a class="nav-link active" href="{% url 'articles:article_create' %}">Create Post</a>
  </li>
</ul>
  <br>
<h3>Welcome to your personal Blog</h3>



{% if ans %}


{% for i in ans %}
		
<div class="mx-auto" style="width: 300px;">
   
	<div class="card">
	{% if i.pic %}	
	<img class="card-img-top" src="{{i.pic.url}}" alt="Card image cap">	
	{% endif %}
 
		<div class="card-body">
		<a class="card-title" href = "{%url 'articles:article_detail' slug=i.slug %}">{{i.title}}</a>
		<p class="card-text">{{i.snippet}}</p>
		<p class="card-text">{{i.time}}</p>
		
			<div class="btn-group" role="group" aria-label="Basic example">
		
    		<a class ="btn btn-primary" href = "{%url 'accounts:article_delete' slug=i.slug %}">Delete Post</a>
    		&nbsp;
    		<a class ="btn btn-primary" href = "{%url 'articles:article_update' slug=i.slug %}">Update Post</a>
    		
    		</div>
    	</div>  
  	</div>
</div>
{% endfor %}
{% endif %}



{% endblock %}

accounts/templates/accounts/sign_up.html
<!-- {% extends 'base.html' %} -->
{% block content %}
<h2>Sign Up</h2>
<form action = "/accounts/sign_up" method ='post'>
{% csrf_token %}
{{form.as_p}}
<input type='submit'  value = 'SignUp'>
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base.html' %}

{% block content %}
<h2>create an article</h2>

<form method ='post' enctype='multipart/form-data'>
{% csrf_token %}
<div class ="form-group">
{{form}}
<!-- 	<label for="exampleInputEmail1">{{form.title}}</label> -->
<!-- 	<input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"> -->
</div>
<button type='submit' class="btn btn-primary">Create</button>
</form>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
<title>Insert title here</title>
{% block content %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% if article %}
<div class="mx-auto" style="width: 300px;">
  	<div class="card" >
		<h2>{{article.title}}</h2>
			{% if article.pic %}


			<img class="card-img-top" src = '{{article.pic.url }}'>
			{% endif %}
				<p>{{article.body}}</p>
				<p>{{article.time}}</p>
	<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>

</div>

</div>
</div>
{% endif %}
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>articles list</h1>

<img src="{% static 'img/LuvUsid.jpg' %}">

<div class ='articles'>
{% for i in obj %}
<div class = 'list'>
<h1><a href="{%url 'articles:article_detail' slug=i.slug %}">{{i.title}}</a></h1>
<p>{{i.snippet}}</p>
<p>{{i.time}}</p>
{% if i.pic %}
<img src = '{{i.pic }}'/>
{% endif %}
</div>
{% endfor %}
</div>
{% endblock %}

templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>About Page</title>
</head>
<body>
<h1>About Us</h1>
<p>Welcome djangonautic</p>
<img src="{% static 'img/image1.jpg' %}">
</body>
</html>

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

<title>Articles</title>

</head>

<body>
<nav>
{% if user.is_authenticated %}
	<form action = "{% url 'accounts:logout_view' %}" method = 'post'>
	
	{% csrf_token %}
	<ul nav class="nav nav-pills">
	  <li class="nav-item">
  <button type='submit' class="btn btn-primary">Sign out</button>
  </li>
	</ul>
	</form>
{% else %}
<!-- 	<li><a href = "{% url 'accounts:login_view'%}">login</a></li> -->
<!-- 	<li><a href = "{% url 'accounts:sign_up' %}">sign up</a></li> -->
{% endif %}
</nav>
{% block content %}
{% endblock %}
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<title>Homepage</title>
<style>
h1{
text-align: center;
}
a
{
text-align: center;
}
</style>
</head>
<body>
<div class = "container-fluid">
<h1>Welcome !</h1>

<!-- <h3>Login </h3> -->
<div class="col-md-20 text-center">
<a class="btn btn-primary" href = "{%url 'accounts:login_view' %}">Login</a>
<!-- <h3>Create Account</h3> -->
<a class="btn btn-primary" href = "{%url 'accounts:sign_up' %}">Create Account</a>
</div>
</div>
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>